In [ ]:
import numpy as np

In [ ]:
A = np.matrix('1.0,2.0,3.0;4.0,5.0,6.0;7.0,8.0,9.0')

A

matrix([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
B = np.identity(3)

B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Atribuindo o valor um para a matriz A[0][0]
A[0,:] = 1/1 * A[0,:]

# Fazendo a operação inversa na matriz identidade
B[0,:] = 1/1 * B[0,:]

A

matrix([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:


B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Zerando os elementos abaixo de A[1][0]
A[1, :] = (-4 * A[0, :]) + A[1, :]

# Fazendo a operação inversa na matriz identidade
B[1, :] = (-4 * B[0, :]) + B[1, :]

A

matrix([[ 1.,  2.,  3.],
        [ 0., -3., -6.],
        [ 7.,  8.,  9.]])

In [ ]:
# Zerando o elemento A[2][0]
A[2, :] = (-7 * A[0, :]) + A[2, :]

# Fazendo a operação inversa na matriz identidade
B[2, :] = (-7 * B[0, :]) + B[2, :]

A

matrix([[  1.,   2.,   3.],
        [  0.,  -3.,  -6.],
        [  0.,  -6., -12.]])

In [ ]:
B

array([[ 1.,  0.,  0.],
       [-4.,  1.,  0.],
       [-7.,  0.,  1.]])

In [ ]:
# Atribuindo o valor um para a matriz A[1][1]
A[1, :] = 1/-3 * A[1, :]

# Fazendo a operação inversa na matriz identidade
B[1, :] = 1/-3 * B[1, :]

A

matrix([[  1.,   2.,   3.],
        [  0.,   1.,   2.],
        [  0.,  -6., -12.]])

In [ ]:
# Zerando o elemento A[0, 1]
A[0, :] = (-2 * A[1, :]) + A[0, :]

# Fazendo a operação inversa na matriz identidade
B[0, :] = (-2 * B[1, :]) + B[0, :]

A

matrix([[  1.,   0.,  -1.],
        [  0.,   1.,   2.],
        [  0.,  -6., -12.]])

In [ ]:
# Zerando o elemento A[2, 1]
A[2, :] = (6 * A[1, :]) + A[2, :]

# Fazendo a operação inversa na matriz identidade
B[2, :] = (6 * B[1, :]) + B[2, :]

A

matrix([[ 1.,  0., -1.],
        [ 0.,  1.,  2.],
        [ 0.,  0.,  0.]])

## Existe matrizes que não possuem inversas

Como podemos ver acima, a terceira linha inteira ficou zerada, isso porque a equação da segunda e da terceira linha são múltiplas

## Inverter matrizes com python


In [ ]:
inv(A)