In [ ]:
import numpy as np

In [ ]:
A = np.matrix('1.0,2.0,4.0;5.0,6.0,7.0')
A

matrix([[1., 2., 4.],
        [5., 6., 7.]])

In [ ]:
np.shape(A)

(2, 3)

In [ ]:
# B = np.zeros((2,3))
B = np.matrix('3.0,4.0,2.0;5.0,9.0,2.0')
B

matrix([[3., 4., 2.],
        [5., 9., 2.]])

In [ ]:
def sumMat(A, B):
  return A + B

def subMat(A, B):
  return A - B

In [ ]:
C = sumMat(A, B)
D = subMat(A, B)

print(C)
print(D)

[[ 4.  6.  6.]
 [10. 15.  9.]]
[[-2. -2.  2.]
 [ 0. -3.  5.]]


## Multiplicação por escalar

In [ ]:
# Escalar
k = 2
E = (k * A)

print(E)

[[ 2.  4.  8.]
 [10. 12. 14.]]


## Multiplicação de matriz

In [ ]:
G = np.matrix('2,3,4;5,2,4;5,2,1;3,7,6')
H = np.matrix('1;2;3')

In [ ]:
# Número de colunas de A têm que ter o mesmo valor do número de linhas de B

print(np.shape(G))
print(np.shape(H))

(4, 3)
(3, 1)


In [ ]:
# A ordem de I vai ser o número de linhas de A e o número de colunas de B

I = G * H

# Error -> I = H * G

print(I)

[[20]
 [21]
 [12]
 [35]]


In [ ]:
J = np.matrix('2,2;2,2')
K = np.matrix('4,4;4,4')

In [ ]:
L = K * J
print(L)

[[ 50 146]
 [ 14  57]]


#### Nota
A x B só vai ser igual a B x A se A e B forem ambas matrizes quadráticas e com
os elementos posicionais iguais.

[LINK](https://mundoeducacao.uol.com.br/matematica/igualdade-entre-matrizes.htm#:~:text=A%20matriz%20A2x2%20%C3%A9,e%20a22%20%3D%20b22.)

## Matriz identidade

In [ ]:
M = np.identity(2)
M

array([[1., 0.],
       [0., 1.]])

In [ ]:
N = K * M
N

matrix([[4., 4.],
        [4., 4.]])

In [ ]:
O = M * K
O

matrix([[4., 4.],
        [4., 4.]])

# Aula 10/05

In [ ]:
import numpy as np

In [ ]:
A = np.matrix('1.0,2.0,3.0;4.0,5.0,6.0;7.0,8.0,9.0')

A

matrix([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
B = np.identity(3)

B

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Multiplicação matricial entre uma matriz quadrada por uma matriz identidade

A nova matriz resultante terá mesma ordem que ambas e também os mesmos elementos que a matriz quadrada, posicionadas de formas iguais.

In [ ]:
C = np.dot(A, B)

C

matrix([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

### A . I_n = A = I_n . A

Só vai ser válida se forem ambas matrizes quadradas de mesma ordem.

In [ ]:
D = np.matrix('2,2,2;3,1,2')

E = np.dot(D, B)
# E = np.dot(B, D) -> Error (número de colunas diferente do número de linhas)
E

matrix([[2., 2., 2.],
        [3., 1., 2.]])

### I_n

Elemento neutro para multiplicação matricial (valor *1* e demais colunas valor *0*)