In [1]:
import numpy as np
from sympy import Symbol, solve

In [50]:
def c_f1(x, y, z):
  return 2*x + y - 2*z - 10

def c_f2(x, y, z):
  return 3*x + 2*y + 2*z - 1

def c_f3(x, y, z):
  return 5*x + 4*y + 3*z - 4


In [51]:
x = Symbol('x')
y = Symbol('y')
z = Symbol('z')

In [52]:
result_class = solve((c_f1(x, y, z), c_f2(x, y, z), c_f3(x, y, z)))


In [53]:
print(result_class)


{x: 1, y: 2, z: -3}


---

## Trabalhando com matrizes linha por linha

Aqui trabalharemos para encontrar os valores de *x, y, z* dentro de um sistema
de equações.

### Modo de fazer

Iremos zerar as equações do sistema de forma que obtermos:
```[
  [x 0 0]
  [0 y 0]
  [0 0 z]
]```

Para isso, nós primeiros alteramos as equações para virar uma matriz, depois alteramos o valor da equação a multiplicando, de forma que o valor final seja zerado, resultando na matriz anterior.

In [ ]:
from fractions import Fraction

In [ ]:
A = np.matrix('1,1,2,9;2,4,-3,1;3,6,-5,0')

In [ ]:
print(A)

[[ 1  1  2  9]
 [ 2  4 -3  1]
 [ 3  6 -5  0]]


In [ ]:
A[2;:] =