# Sistemas de Equações Lineares
## Multiplicação de matrizes de ordem xn por outra matriz de ordem 1n

A x->
[a11 a12 a13]
[a21 a22 a23]
[a31 a32 a33]

In [ ]:
import numpy as np

In [ ]:
A = np.matrix("1.0, 1.0, 2.0, 9.0; 2.0, 4.0, -3.0, 1.0; 3.0, 6.0, -5.0, 0.0")
print(A)

[[ 1.  1.  2.  9.]
 [ 2.  4. -3.  1.]
 [ 3.  6. -5.  0.]]


### Objetivo
Nosso objetivo é transformar a matriz dada em uma matriz identidade com a diagonal principal igual a 1 e os demais elementos igual a zero.

Com isso, temos que a última coluna da matriz será igual a resolução do sistema linaer com dadas equações.

Nosso sistema é:

x + y + 2z = 9
2x + 4y - 3z = 1
3x + 6y - 5z = 0

In [ ]:
A[1,:] = -2 * A[0,:] + A[1, :]
print(A)

[[  1.   1.   2.   9.]
 [  0.   2.  -7. -17.]
 [  3.   6.  -5.   0.]]


In [ ]:
A[2,:] = -3 * A[0,:] + A[2,:]
print(A)

[[  1.   1.   2.   9.]
 [  0.   2.  -7. -17.]
 [  0.   3. -11. -27.]]


In [ ]:
A[0,:] = A[0,:] - (A[1, :] / 2)
print(A)

[[  1.    0.    5.5  17.5]
 [  0.    2.   -7.  -17. ]
 [  0.    3.  -11.  -27. ]]


In [ ]:
A[1,:] = A[1,:] / 2
print(A)

[[  1.    0.    5.5  17.5]
 [  0.    1.   -3.5  -8.5]
 [  0.    3.  -11.  -27. ]]


In [ ]:
A[2,:] = -3 * A[1,:] + A[2,:]
print(A)

[[ 1.   0.   5.5 17.5]
 [ 0.   1.  -3.5 -8.5]
 [ 0.   0.  -0.5 -1.5]]


In [ ]:
A[0,:] = 2.5 * A[2,:] + A[0,:]
print(A)

[[ 1.    0.    4.25 13.75]
 [ 0.    1.   -3.5  -8.5 ]
 [ 0.    0.   -0.5  -1.5 ]]


In [ ]:
A[2,:] = -(A[2,:] / 2)
print(A)

[[ 1.    0.    4.25 13.75]
 [ 0.    1.   -3.5  -8.5 ]
 [-0.   -0.    0.25  0.75]]


In [ ]:
A[1,:] = 3 * A[2,:] + A[1,:]
print(A)

[[ 1.    0.    4.25 13.75]
 [ 0.    1.   -2.75 -6.25]
 [-0.   -0.    0.25  0.75]]


### Resultado

O resultado do nosso sitema será 1, 2 e 3, respectivamente

---

### Conferindo

Para conferir, iremos multiplicar a matriz inicial (sem a ultima coluna) com o resultado encontrado, o resultado será uma matriz com os valores acima

In [ ]:
a_prova = np.matrix("1, 1, 2; 2, 4, -3; 3, 6, -5")
b_prova = np.matrix("1; 2; 3")

m_final = a_prova.dot(b_prova)
print(m_final)

[[9]
 [1]
 [0]]
